package SecureBlue;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheThoetha
 */
public class DeviceIntroPanel extends java.awt.Panel {

    /**
     * Creates new form DeviceIntroPanel
     */
    public DeviceIntroPanel() {
        initComponents();
        jTextPane1.setText("<html>\n" +
"	<head>\n" +
"		<title>HTML Online Editor Sample</title>\n" +
"	</head>\n" +
"	<body>\n" +
"		<h1>\n" +
"			Online HTML Editor</h1>\n" +
"		<p>\n" +
"			This is an online HTML editor. Try editing this text area - go on!</p>\n" +
"		<p>\n" +
"			Here is some <strong>sample bold text</strong>.&nbsp;</p>\n" +
"		<p>\n" +
"			Here is a checklist for a good online editor:</p>\n" +
"		<ul>\n" +
"			<li>\n" +
"				Is it a WYSIWYG editor? (WYSIWYG means &quot;What You See Is What You Get&quot; - just like this editor!)</li>\n" +
"			<li>\n" +
"				Does it generate valid HTML code?</li>\n" +
"			<li>\n" +
"				Is it quick and easy?</li>\n" +
"			<li>\n" +
"				Is it... FREE?</li>\n" +
"		</ul>\n" +
"		<p>\n" +
"			Feel free to use this online HTML editor for generating HTML code for your own website, MySpace page, etc. To view the source code, simply click on the &quot;Source&quot; button above.</p>\n" +
"	</body>\n" +
"</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jToggleButton1.setText("jToggleButton1");

        setMaximumSize(new java.awt.Dimension(445, 406));
        setMinimumSize(new java.awt.Dimension(445, 406));
        setPreferredSize(new java.awt.Dimension(445, 406));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
